### PR TITLE
Use nc to test opening a connection

### PR DESCRIPTION
**Pull request by marcuschangarm**
Also redirect stderr to output log.

### CODE REVIEW

**Comment by marcuschangarm** [comment]
Creates the following output:
```
Fri May 27 09:04:38 PDT 2022
PING api.snapcraft.io (185.125.188.57) 56(84) bytes of data.

--- api.snapcraft.io ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 118.866/118.866/118.866/0.000 ms
PING lwm2m.us-east-1.mbedcloud.com (34.234.72.174) 56(84) bytes of data.

--- lwm2m.us-east-1.mbedcloud.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 42.952/42.952/42.952/0.000 ms
Connection to api.snapcraft.io 443 port [tcp/https] succeeded!
Connection to lwm2m.us-east-1.mbedcloud.com 443 port [tcp/https] succeeded!
Write openssl output to /root/snap/edge-tools/common/test-lwm2m.txt
TLS to LwM2M server: success
```

**Comment by marcuschangarm** [comment]
@JanneKiiskila how about this for testing connectivity in general?

**Comment by JanneKiiskila** [comment]
`nc` gives an succesfull output in case of any connectivity there, even if there's an intrusive firewall in-between. So, it might give a false sense of "success".

**Comment by marcuschangarm** [comment]
> for the lwm2m.us-east-1.mbedcloud.com port 443 is of no interest

It's another data point - if HTTPS works but CoAPS doesn't, we know the CoAPS port is blocked somewhere but the Pelion domain itself is fine.

**Review by JanneKiiskila — APPROVED** [review]

**Pull request merged**
